[package]
name = "gm_cpreprocessor"
version = "1.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
opt-level = "s"

[dependencies]
gmod = "15"
cc = "1"
lazy_static = "1"
uuid = { version = "0", features = ["v4"] }